if status is-interactive
alias up="sudo xbps-install -Suv ; flatpak update ; multipull ; cd ~"
alias xi="sudo xbps-install"
alias xq="xbps-query -Rs"
alias xrm="sudo xbps-remove"
alias xarm="sudo xbps-remove -R -O"
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias arm="sudo xbps-remove -yo"
alias xorph="sudo xbps-remove -Oo"
alias multipull="cd ~/Git; find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} pull \;"
alias fru="flatpak remove --unused"
alias hc="history clear"
alias manpkg="xbps-query -l -m | batcat -p"
alias brightup="xrandr --output DVI-I-1 --brightness 1"
alias brightdown="xrandr --output DVI-I-1 --brightness 0.5 ; redshift -O 3600K" 
alias wads="cd /home/mike/wads"
alias cde="cd /home/mike/Games/eternity-4.04.02/build/eternity"
alias mobo="cat /sys/devices/virtual/dmi/id/board_{vendor,name,version}"
alias birthday="stat -c %w /"
alias remconf="dpkg -l | grep '^rc' | awk '{print $2}' | sudo xargs dpkg --purge"
alias remconf2="dpkg -l | grep '^rc' | awk '{print $2}' | xargs sudo apt-get --purge remove -y"
alias fishconf="vim ~/.config/fish/config.fish"
alias fishsource="source ~/.config/fish/config.fish"
alias timefix="sudo hwclock --systohc"
alias lsf="export SDL_FORCE_SOUNDFONTS=1"
alias asf="export SDL_SOUNDFONTS=/home/mike/wads/SC-55.sf2"
alias reboot="sudo reboot"
end
